In [8]:
# import random
# from itertools import permutations
# import pandas as pd

# # Set seed for reproducibility
# random.seed(123)

# # Define the pool of syllabus items
# syllabus_pool = ["barget", "bimdah", "chelad", "dingep", "fisslin", "goorshell",
#                  "haagle", "jeelow", "limeber", "makkot", "nellby", "pakrid",
#                  "rakken", "sumbark"]

# # Randomly select 10 items from the pool
# selected_items = random.sample(syllabus_pool, 10)

# # Generate all possible permutations of the selected items
# all_permutations = list(permutations(selected_items, 3))

# # Filter out invalid permutations (those with repeated items)
# valid_permutations = [p for p in all_permutations if len(set(p)) == len(p)]

# # Randomly select 20 valid permutations
# selected_permutations = random.sample(valid_permutations, 20)

# # Create the initial DataFrame
# df = pd.DataFrame({
#     'trial': range(1, 21),
#     'item1': [p[0] for p in selected_permutations],
#     'item2': [p[1] for p in selected_permutations],
#     'item3': [p[2] for p in selected_permutations]
# })

# # Identify remaining items for case markers
# remaining_items = list(set(syllabus_pool) - set(selected_items))

# # Randomly select 3 items to be used as case markers
# casemarker_items = random.sample(remaining_items, 3)

# # Add case markers to the DataFrame
# df['casemarker1'] = casemarker_items[0]
# df['casemarker2'] = casemarker_items[1]
# df['casemarker3'] = casemarker_items[2]

# # Create a concatenated column for items and case markers
# df['final'] = df['item1'] + " " + df['casemarker1'] + " " + df['item2'] + " " + df['casemarker2'] + " " + df['item3'] + " " + df['casemarker3']

# # Create a new DataFrame with swapped case markers
# df_new = df.copy()

# # Identify 50% of rows to swap in df_new
# swap_rows = random.sample(range(len(df_new)), int(len(df_new) * 0.5))

# # Swap casemarkers in df_new for the identified rows
# for row in swap_rows:
#     df_new.at[row, 'casemarker2'], df_new.at[row, 'casemarker3'] = df_new.at[row, 'casemarker3'], df_new.at[row, 'casemarker2']

# # Update the 'final' column in df_new
# df_new['final'] = df_new['item1'] + " " + df_new['casemarker1'] + " " + df_new['item2'] + " " + df_new['casemarker2'] + " " + df_new['item3'] + " " + df_new['casemarker3']


# # Label the conditions
# df['condition'] = "correlated"
# df_new['condition'] = "isolated"

# # Combine the original and new DataFrames
# combined_df = pd.concat([df, df_new], ignore_index=True)
# combined_df

In [1]:
import random
from itertools import permutations
import pandas as pd

# Set seed for reproducibility
random.seed(123)

# Define the pool of syllabus items
syllabus_pool = ["barget", "bimdah", "chelad", "dingep", "fisslin", "goorshell",
                 "haagle", "jeelow", "limeber", "makkot", "nellby", "pakrid",
                 "rakken", "sumbark"]

# Randomly select 10 items from the pool
selected_items = random.sample(syllabus_pool, 10)

# Generate all possible permutations of the selected items
all_permutations = list(permutations(selected_items, 3))

# Filter out invalid permutations (those with repeated items)
valid_permutations = [p for p in all_permutations if len(set(p)) == len(p)]

# Randomly select 20 valid permutations
selected_permutations = random.sample(valid_permutations, 20)

# Create the initial DataFrame
df = pd.DataFrame({
    'trial': range(1, 21),
    'item1': [p[0] for p in selected_permutations],
    'item2': [p[1] for p in selected_permutations],
    'item3': [p[2] for p in selected_permutations]
})

# Identify remaining items for case markers
remaining_items = list(set(syllabus_pool) - set(selected_items))

# Randomly select 3 items to be used as case markers
casemarker_items = random.sample(remaining_items, 3)

# Randomly select 3 items to be used as case markers
casemarker_items = random.sample(remaining_items, 3)

# Add case markers to the DataFrame
df['casemarker1'] = casemarker_items[0]
df['casemarker2'] = casemarker_items[1]
df['casemarker3'] = casemarker_items[2]

# Create a list of case marker combinations
case_marker_combinations = ["correlated", "isolated-left", "isolated-center", "isolated-right"]

# Create an empty list to store rows
rows = []

# Create rows for each combination of case markers
for combination in case_marker_combinations:
    # Create a new DataFrame with swapped case markers
    df_new = df.copy()
    
    # Function to swap case markers for a given row
    def swap_case_markers(row, combination):
        if combination == "isolated-left":
            row['casemarker2'], row['casemarker3'] = row['casemarker3'], row['casemarker2']
        elif combination == "isolated-center":
            row['casemarker1'], row['casemarker3'] = row['casemarker3'], row['casemarker1']
        elif combination == "isolated-right":
            row['casemarker1'], row['casemarker2'] = row['casemarker2'], row['casemarker1']
        return row

    # Identify 50% of rows to swap in df_new
    swap_rows = random.sample(range(len(df_new)), int(len(df_new) * 0.5))

    # Swap casemarkers in df_new for the identified rows
    for row in swap_rows:
        df_new.iloc[row] = swap_case_markers(df_new.iloc[row], combination)

    # Update the 'final' column in df_new
    df_new['final'] = df_new['item1'] + " " + df_new['casemarker1'] + " " + df_new['item2'] + " " + df_new['casemarker2'] + " " + df_new['item3'] + " " + df_new['casemarker3']

    # Label the conditions
    df_new['condition'] = combination
    
    rows.append(df_new)

# Combine the DataFrames for different combinations
combined_df = pd.concat(rows, ignore_index=True)
combined_df

/var/folders/5r/pnlff12n2d55g65_tnn3b1pw0000gn/T/ipykernel_19046/3091190978.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  row['casemarker2'], row['casemarker3'] = row['casemarker3'], row['casemarker2']
/var/folders/5r/pnlff12n2d55g65_tnn3b1pw0000gn/T/ipykernel_19046/3091190978.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  row['casemarker1'], row['casemarker3'] = row['casemarker3'], row['casemarker1']
/var/folders/5r/pnlff12n2d55g65_tnn3b1pw0000gn/T/ipykernel_19046/3091190978.py:65: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  row['casemarker1'], row['casemarker2'] = row['casemarker2'], row['casemarker1']

,trial,item1,item2,item3,casemarker1,casemarker2,casemarker3,final,condition
0,1,rakken,dingep,pakrid,chelad,jeelow,nellby,rakken chelad dingep jeelow pakrid nellby,correlated
1,2,rakken,makkot,pakrid,chelad,jeelow,nellby,rakken chelad makkot jeelow pakrid nellby,correlated
2,3,barget,dingep,sumbark,chelad,jeelow,nellby,barget chelad dingep jeelow sumbark nellby,correlated
3,4,bimdah,haagle,pakrid,chelad,jeelow,nellby,bimdah chelad haagle jeelow pakrid nellby,correlated
4,5,fisslin,goorshell,haagle,chelad,jeelow,nellby,fisslin chelad goorshell jeelow haagle nellby,correlated
...,...,...,...,...,...,...,...,...,...
75,16,pakrid,haagle,bimdah,jeelow,chelad,nellby,pakrid jeelow haagle chelad bimdah nellby,isolated-right
76,17,barget,goorshell,makkot,jeelow,chelad,nellby,barget jeelow goorshell chelad makkot nellby,isolated-right
77,18,barget,fisslin,makkot,jeelow,chelad,nellby,barget jeelow fisslin chelad makkot nellby,isolated-right
78,19,rakken,pakrid,haagle,chelad,jeelow,nellby,rakken chelad pakrid jeelow haagle nellby,isolated-right
79,20,sumbark,haagle,rakken,chelad,jeelow,nellby,sumbark chelad haagle jeelow rakken nellby,isolated-right

In [19]:
test_permulations = list(set(valid_permutations) - set(selected_permutations))

700

In [26]:
# Randomly select 48 permutations from the remaining 20
test_permutations = random.sample(list(set(valid_permutations) - set(selected_permutations)),48)

# Create the test DataFrame
test_df = pd.DataFrame({
    'trial': range(1, 49),
    'item1': [p[0] for p in test_permutations],
    'item2': [p[1] for p in test_permutations],
    'item3': [p[2] for p in test_permutations]
})

# Randomly select 3 items to be used as case markers
casemarker_items = random.sample(remaining_items, 3)

# Randomly select 3 items to be used as case markers
casemarker_items = random.sample(remaining_items, 3)

# Add case markers to the DataFrame
test_df['casemarker1'] = casemarker_items[0]
test_df['casemarker2'] = casemarker_items[1]
test_df['casemarker3'] = casemarker_items[2]



# Create a list of case marker combinations
case_marker_combinations = ["correlated", "isolated-left", "isolated-center", "isolated-right"]

# Create an empty list to store rows
rows = []

# Create rows for each combination of case markers
for combination in case_marker_combinations:
    # Create a new DataFrame with swapped case markers
    df_new = test_df.copy()
    
    # Function to swap case markers for a given row
    def swap_case_markers(row, combination):
        if combination == "isolated-left":
            row['casemarker2'], row['casemarker3'] = row['casemarker3'], row['casemarker2']
        elif combination == "isolated-center":
            row['casemarker1'], row['casemarker3'] = row['casemarker3'], row['casemarker1']
        elif combination == "isolated-right":
            row['casemarker1'], row['casemarker2'] = row['casemarker2'], row['casemarker1']
        return row

    # Identify 50% of rows to swap in df_new
    swap_rows = random.sample(range(len(df_new)), int(len(df_new) * 0.5))

    # Swap casemarkers in df_new for the identified rows
    for row in swap_rows:
        df_new.iloc[row] = swap_case_markers(df_new.iloc[row], combination)

    # Update the 'final' column in df_new
    df_new['final'] = df_new['item1'] + " " + df_new['casemarker1'] + " " + df_new['item2'] + " " + df_new['casemarker2'] + " " + df_new['item3'] + " " + df_new['casemarker3']

    # Label the conditions
    df_new['condition'] = combination
    
    rows.append(df_new)

test_combined_df = pd.concat(rows, ignore_index=True)
test_combined_df

/var/folders/5r/pnlff12n2d55g65_tnn3b1pw0000gn/T/ipykernel_19046/2287108947.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  row['casemarker2'], row['casemarker3'] = row['casemarker3'], row['casemarker2']
/var/folders/5r/pnlff12n2d55g65_tnn3b1pw0000gn/T/ipykernel_19046/2287108947.py:41: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  row['casemarker1'], row['casemarker3'] = row['casemarker3'], row['casemarker1']
/var/folders/5r/pnlff12n2d55g65_tnn3b1pw0000gn/T/ipykernel_19046/2287108947.py:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  row['casemarker1'], row['casemarker2'] = row['casemarker2'], row['casemarker1']

,trial,item1,item2,item3,casemarker1,casemarker2,casemarker3,final,condition
0,1,rakken,bimdah,sumbark,nellby,jeelow,chelad,rakken nellby bimdah jeelow sumbark chelad,correlated
1,2,makkot,pakrid,haagle,nellby,jeelow,chelad,makkot nellby pakrid jeelow haagle chelad,correlated
2,3,goorshell,rakken,fisslin,nellby,jeelow,chelad,goorshell nellby rakken jeelow fisslin chelad,correlated
3,4,dingep,fisslin,goorshell,nellby,jeelow,chelad,dingep nellby fisslin jeelow goorshell chelad,correlated
4,5,haagle,barget,rakken,nellby,jeelow,chelad,haagle nellby barget jeelow rakken chelad,correlated
...,...,...,...,...,...,...,...,...,...
187,44,haagle,rakken,fisslin,nellby,jeelow,chelad,haagle nellby rakken jeelow fisslin chelad,isolated-right
188,45,haagle,fisslin,makkot,nellby,jeelow,chelad,haagle nellby fisslin jeelow makkot chelad,isolated-right
189,46,rakken,sumbark,fisslin,nellby,jeelow,chelad,rakken nellby sumbark jeelow fisslin chelad,isolated-right
190,47,barget,fisslin,goorshell,nellby,jeelow,chelad,barget nellby fisslin jeelow goorshell chelad,isolated-right
191,48,goorshell,haagle,barget,jeelow,nellby,chelad,goorshell jeelow haagle nellby barget chelad,isolated-right

#### DONE - Need to change isolated conditon to middle-right, left-right, left-middle

### Foil Generation 
##### generating foils (visual), they are two types of foil
#### type 1 (6 trial each block): transposition. for example: ABC, can be transposed into two way: BCA, CAB
#### type 2 (6 trial each block): one item change, for example: ABC can be paired with DBC (D is randomly chose from 10-3 = 7 possible symbols). 
#### There are a total of 3 possible changes (left place, middle, right place), creat two trials for each of the change

In [29]:
# Type1 
## GENERATING TEST SET
test_cond_corr = test_combined_df[test_combined_df['condition']=='correlated']
test_cond_iso_l = test_combined_df[test_combined_df['condition']=='isolated-left']
test_cond_iso_c = test_combined_df[test_combined_df['condition']=='isolated-center']
test_cond_iso_r = test_combined_df[test_combined_df['condition']=='isolated-right']

test_cond_corr = test_cond_corr.sample(n=12).reset_index(drop=True)
test_cond_iso_l = test_cond_iso_l.sample(n=12).reset_index(drop=True)
test_cond_iso_c = test_cond_iso_c.sample(n=12).reset_index(drop=True)
test_cond_iso_r = test_cond_iso_r.sample(n=12).reset_index(drop=True)

test_df = pd.concat([test_cond_corr, test_cond_iso_l,test_cond_iso_c,test_cond_iso_r], axis=0).reset_index(drop=True)

# foil_categories
# Define the item categories
foil_category_1 = ['transposition']*6
foil_category_2 = ['itemchange']*6

foil_categories = foil_category_1 + foil_category_2 + foil_category_1 + foil_category_2 +foil_category_1 + foil_category_2 + foil_category_1 + foil_category_2
test_df['foil_category'] = foil_categories

In [30]:
test_df[test_df['condition']=='isolated-left']

,trial,item1,item2,item3,casemarker1,casemarker2,casemarker3,final,condition,foil_category
12,21,makkot,sumbark,barget,nellby,chelad,jeelow,makkot nellby sumbark chelad barget jeelow,isolated-left,transposition
13,17,dingep,haagle,rakken,nellby,chelad,jeelow,dingep nellby haagle chelad rakken jeelow,isolated-left,transposition
14,27,bimdah,dingep,makkot,nellby,jeelow,chelad,bimdah nellby dingep jeelow makkot chelad,isolated-left,transposition
15,1,rakken,bimdah,sumbark,nellby,chelad,jeelow,rakken nellby bimdah chelad sumbark jeelow,isolated-left,transposition
16,22,fisslin,barget,dingep,nellby,jeelow,chelad,fisslin nellby barget jeelow dingep chelad,isolated-left,transposition
17,46,rakken,sumbark,fisslin,nellby,jeelow,chelad,rakken nellby sumbark jeelow fisslin chelad,isolated-left,transposition
18,7,haagle,rakken,makkot,nellby,jeelow,chelad,haagle nellby rakken jeelow makkot chelad,isolated-left,itemchange
19,47,barget,fisslin,goorshell,nellby,chelad,jeelow,barget nellby fisslin chelad goorshell jeelow,isolated-left,itemchange
20,30,dingep,goorshell,makkot,nellby,chelad,jeelow,dingep nellby goorshell chelad makkot jeelow,isolated-left,itemchange
21,10,haagle,bimdah,dingep,nellby,chelad,jeelow,haagle nellby bimdah chelad dingep jeelow,isolated-left,itemchange
22,16,haagle,makkot,rakken,nellby,jeelow,chelad,haagle nellby makkot jeelow rakken chelad,isolated-left,itemchange
23,23,makkot,sumbark,bimdah,nellby,jeelow,chelad,makkot nellby sumbark jeelow bimdah chelad,isolated-left,itemchange

In [31]:
import random
from itertools import permutations
def generate_transposition_foil(items,):
    

    cyclic_permutations = []

    for perm in permutations(items):
        cyclic_permutation = ','.join(perm)
        if cyclic_permutation not in cyclic_permutations:
            cyclic_permutations.append(cyclic_permutation)

    trans_foils = [[foil] for foil in cyclic_permutations[1:]]
    return trans_foils

In [32]:
test_df_transposition = test_df[test_df['foil_category']=='transposition']
test_df_itemchange = test_df[test_df['foil_category']=='itemchange']


# TRANSPOSITION
list_of_foils = []
print("Generating Transposition Foils.")
for row in test_df_transposition[['item1','item2','item3']].iterrows():
    target_items = row[1].to_list()
    trans_foils = generate_transposition_foil(target_items)
    trans_foils = [item[0].split(',') for item in trans_foils]
    transposition_foil = random.choice(trans_foils)
    list_of_foils.append(transposition_foil)
test_df_transposition['foil'] = list_of_foils

# ITEM CHANGE
print("Generating Item Change Foils.")
list_of_foils = []
for row in test_df_itemchange[['item1','item2','item3']].iterrows():
    target_items = row[1].to_list()
    ##print(target_items)
    possibilities =  list(set(selected_items) - set(target_items))
    #print(possibilities)
    item_change = random.choice(possibilities)
    positions = [0,1,2] # left, center, middle
    position_selection = random.choice(positions)
    #print(item_change)
    #print(position_selection)
    
    itemchange_foils = target_items
    itemchange_foils[position_selection] = item_change
    list_of_foils.append(itemchange_foils)
    
    
test_df_itemchange['foil'] = list_of_foils


# REORDERING 

test_df = pd.concat([test_df_transposition, test_df_itemchange],axis=0)

# reordering
corr_df = test_df[test_df['condition']=='correlated']
iso_left_df = test_df[test_df['condition']=='isolated-left']
iso_center_df = test_df[test_df['condition']=='isolated-center']
iso_right_df = test_df[test_df['condition']=='isolated-right']

final_test_df = pd.concat([corr_df,iso_left_df,iso_center_df,iso_right_df],axis=0)
final_test_df

Generating Transposition Foils.
Generating Item Change Foils.

/var/folders/5r/pnlff12n2d55g65_tnn3b1pw0000gn/T/ipykernel_19046/602159972.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_df_transposition['foil'] = list_of_foils
/var/folders/5r/pnlff12n2d55g65_tnn3b1pw0000gn/T/ipykernel_19046/602159972.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_df_itemchange['foil'] = list_of_foils

,trial,item1,item2,item3,casemarker1,casemarker2,casemarker3,final,condition,foil_category,foil
0,10,haagle,bimdah,dingep,nellby,jeelow,chelad,haagle nellby bimdah jeelow dingep chelad,correlated,transposition,"[dingep, haagle, bimdah]"
1,23,makkot,sumbark,bimdah,nellby,jeelow,chelad,makkot nellby sumbark jeelow bimdah chelad,correlated,transposition,"[makkot, bimdah, sumbark]"
2,24,bimdah,rakken,dingep,nellby,jeelow,chelad,bimdah nellby rakken jeelow dingep chelad,correlated,transposition,"[bimdah, dingep, rakken]"
3,31,dingep,fisslin,barget,nellby,jeelow,chelad,dingep nellby fisslin jeelow barget chelad,correlated,transposition,"[barget, dingep, fisslin]"
4,8,bimdah,dingep,barget,nellby,jeelow,chelad,bimdah nellby dingep jeelow barget chelad,correlated,transposition,"[dingep, barget, bimdah]"
5,17,dingep,haagle,rakken,nellby,jeelow,chelad,dingep nellby haagle jeelow rakken chelad,correlated,transposition,"[rakken, haagle, dingep]"
6,18,bimdah,makkot,pakrid,nellby,jeelow,chelad,bimdah nellby makkot jeelow pakrid chelad,correlated,itemchange,"[bimdah, makkot, rakken]"
7,3,goorshell,rakken,fisslin,nellby,jeelow,chelad,goorshell nellby rakken jeelow fisslin chelad,correlated,itemchange,"[goorshell, bimdah, fisslin]"
8,48,goorshell,haagle,barget,nellby,jeelow,chelad,goorshell nellby haagle jeelow barget chelad,correlated,itemchange,"[goorshell, haagle, pakrid]"
9,37,barget,dingep,fisslin,nellby,jeelow,chelad,barget nellby dingep jeelow fisslin chelad,correlated,itemchange,"[barget, sumbark, fisslin]"
10,14,goorshell,fisslin,rakken,nellby,jeelow,chelad,goorshell nellby fisslin jeelow rakken chelad,correlated,itemchange,"[goorshell, dingep, rakken]"
11,44,haagle,rakken,fisslin,nellby,jeelow,chelad,haagle nellby rakken jeelow fisslin chelad,correlated,itemchange,"[makkot, rakken, fisslin]"
12,21,makkot,sumbark,barget,nellby,chelad,jeelow,makkot nellby sumbark chelad barget jeelow,isolated-left,transposition,"[makkot, barget, sumbark]"
13,17,dingep,haagle,rakken,nellby,chelad,jeelow,dingep nellby haagle chelad rakken jeelow,isolated-left,transposition,"[dingep, rakken, haagle]"
14,27,bimdah,dingep,makkot,nellby,jeelow,chelad,bimdah nellby dingep jeelow makkot chelad,isolated-left,transposition,"[dingep, bimdah, makkot]"
15,1,rakken,bimdah,sumbark,nellby,chelad,jeelow,rakken nellby bimdah chelad sumbark jeelow,isolated-left,transposition,"[sumbark, rakken, bimdah]"
16,22,fisslin,barget,dingep,nellby,jeelow,chelad,fisslin nellby barget jeelow dingep chelad,isolated-left,transposition,"[barget, dingep, fisslin]"
17,46,rakken,sumbark,fisslin,nellby,jeelow,chelad,rakken nellby sumbark jeelow fisslin chelad,isolated-left,transposition,"[sumbark, rakken, fisslin]"
18,7,haagle,rakken,makkot,nellby,jeelow,chelad,haagle nellby rakken jeelow makkot chelad,isolated-left,itemchange,"[barget, rakken, makkot]"
19,47,barget,fisslin,goorshell,nellby,chelad,jeelow,barget nellby fisslin chelad goorshell jeelow,isolated-left,itemchange,"[barget, fisslin, pakrid]"
20,30,dingep,goorshell,makkot,nellby,chelad,jeelow,dingep nellby goorshell chelad makkot jeelow,isolated-left,itemchange,"[haagle, goorshell, makkot]"
21,10,haagle,bimdah,dingep,nellby,chelad,jeelow,haagle nellby bimdah chelad dingep jeelow,isolated-left,itemchange,"[sumbark, bimdah, dingep]"
22,16,haagle,makkot,rakken,nellby,jeelow,chelad,haagle nellby makkot jeelow rakken chelad,isolated-left,itemchange,"[haagle, pakrid, rakken]"
23,23,makkot,sumbark,bimdah,nellby,jeelow,chelad,makkot nellby sumbark jeelow bimdah chelad,isolated-left,itemchange,"[makkot, sumbark, goorshell]"
24,33,rakken,sumbark,goorshell,nellby,jeelow,chelad,rakken nellby sumbark jeelow goorshell chelad,isolated-center,transposition,"[sumbark, goorshell, rakken]"
25,39,pakrid,haagle,barget,chelad,jeelow,nellby,pakrid chelad haagle jeelow barget nellby,isolated-center,transposition,"[pakrid, barget, haagle]"
26,38,rakken,pakrid,barget,nellby,jeelow,chelad,rakken nellby pakrid jeelow barget chelad,isolated-center,transposition,"[pakrid, barget, rakken]"
27,8,bimdah,dingep,barget,nellby,jeelow,chelad,bimdah nellby dingep jeelow barget chelad,isolated-center,transposition,"[dingep, barget, bimdah]"
28,23,makkot,sumbark,bimdah,nellby,jeelow,chelad,makkot nellby sumbark jeelow bimdah chelad,isolated-center,transposition,"[sumbark, makkot, bimdah]"
29,9,pakrid,barget,bimdah,chelad,jeelow,nellby,pakrid chelad barget jeelow bimdah nellby,isolated-center,transposition,"[bimdah, barget, pakrid]"
30,32,sumbark,makkot,haagle,chelad,jeelow,nellby,sumbark chelad makkot jeelow haagle nellby,isolated-center,itemchange,"[sumbark, dingep, haagle]"
31,29,goorshell,bimdah,sumbark,nellby,jeelow,chelad,goorshell nellby bimdah jeelow sumbark chelad,isolated-center,itemchange,"[goorshell, makkot, sumbark]"
32,16,haagle,makkot,rakken,nellby,jeelow,chelad,haagle nellby makkot jeelow rakken chelad,isolated-center,itemchange,"[haagle, barget, rakken]"
33,35,fisslin,bimdah,makkot,nellby,jeelow,chelad,fisslin nellby bimdah jeelow makkot chelad,isolated-center,itemchange,"[fisslin, rakken, makkot]"
34,42,sumbark,pakrid,goorshell,chelad,jeelow,nellby,sumbark chelad pakrid jeelow goorshell nellby,isolated-center,itemchange,"[dingep, pakrid, goorshell]"
35,34,rakken,fisslin,dingep,chelad,jeelow,nellby,rakken chelad fisslin jeelow dingep nellby,isolated-center,itemchange,"[bimdah, fisslin, dingep]"
36,37,barget,dingep,fisslin,jeelow,nellby,chelad,barget jeelow dingep nellby fisslin chelad,isolated-right,transposition,"[barget, fisslin, dingep]"
37,4,dingep,fisslin,goorshell,jeelow,nellby,chelad,dingep jeelow fisslin nellby goorshell chelad,isolated-right,transposition,"[fisslin, goorshell, dingep]"
38,11,bimdah,haagle,fisslin,nellby,jeelow,chelad,bimdah nellby haagle jeelow fisslin chelad,isolated-right,transposition,"[haagle, bimdah, fisslin]"
39,44,haagle,rakken,fisslin,nellby,jeelow,chelad,haagle nellby rakken jeelow fisslin chelad,isolated-right,transposition,"[fisslin, haagle, rakken]"
40,43,haagle,barget,dingep,jeelow,nellby,chelad,haagle jeelow barget nellby dingep chelad,isolated-right,transposition,"[barget, haagle, dingep]"
41,42,sumbark,pakrid,goorshell,jeelow,nellby,chelad,sumbark jeelow pakrid nellby goorshell chelad,isolated-right,transposition,"[goorshell, sumbark, pakrid]"
42,34,rakken,fisslin,dingep,jeelow,nellby,chelad,rakken jeelow fisslin nellby dingep chelad,isolated-right,itemchange,"[rakken, fisslin, bimdah]"
43,35,fisslin,bimdah,makkot,nellby,jeelow,chelad,fisslin nellby bimdah jeelow makkot chelad,isolated-right,itemchange,"[fisslin, bimdah, sumbark]"
44,12,rakken,bimdah,makkot,nellby,jeelow,chelad,rakken nellby bimdah jeelow makkot chelad,isolated-right,itemchange,"[rakken, bimdah, dingep]"
45,30,dingep,goorshell,makkot,jeelow,nellby,chelad,dingep jeelow goorshell nellby makkot chelad,isolated-right,itemchange,"[dingep, sumbark, makkot]"
46,33,rakken,sumbark,goorshell,nellby,jeelow,chelad,rakken nellby sumbark jeelow goorshell chelad,isolated-right,itemchange,"[rakken, haagle, goorshell]"
47,21,makkot,sumbark,barget,nellby,jeelow,chelad,makkot nellby sumbark jeelow barget chelad,isolated-right,itemchange,"[makkot, rakken, barget]"

### Archived Logic for Test

In [69]:

# Randomly select 12 items from selected_permutations
test_selected_permutations = random.sample(selected_permutations, 12)

# Identify the remaining items for case markers
remaining_items = list(set(syllabus_pool) - set(selected_items))

# Randomly select 12 items to be used as case markers for the test_df
test_casemarker_items = random.sample(remaining_items, 3)

# Create the initial DataFrame for the test_df
test_df = pd.DataFrame({
    'trial': range(1, 13),
    'item1': [p[0] for p in test_selected_permutations],
    'item2': [p[1] for p in test_selected_permutations],
    'item3': [p[2] for p in test_selected_permutations],
    'casemarker1': test_casemarker_items[0],  
    'casemarker2': test_casemarker_items[1],  
    'casemarker3': test_casemarker_items[2],
})

# Create a concatenated column for items and case markers in test_df
test_df['target'] = test_df['item1'] + " " + test_df['casemarker1'] + " " + test_df['item2'] + " " + test_df['casemarker2'] + " " + test_df['item3'] + " " + test_df['casemarker3']

test_df

,trial,item1,item2,item3,casemarker1,casemarker2,casemarker3,target
0,1,barget,fisslin,makkot,chelad,limeber,jeelow,barget chelad fisslin limeber makkot jeelow
1,2,pakrid,haagle,bimdah,chelad,limeber,jeelow,pakrid chelad haagle limeber bimdah jeelow
2,3,barget,goorshell,makkot,chelad,limeber,jeelow,barget chelad goorshell limeber makkot jeelow
3,4,fisslin,haagle,bimdah,chelad,limeber,jeelow,fisslin chelad haagle limeber bimdah jeelow
4,5,barget,fisslin,haagle,chelad,limeber,jeelow,barget chelad fisslin limeber haagle jeelow
5,6,goorshell,makkot,sumbark,chelad,limeber,jeelow,goorshell chelad makkot limeber sumbark jeelow
6,7,rakken,dingep,pakrid,chelad,limeber,jeelow,rakken chelad dingep limeber pakrid jeelow
7,8,sumbark,fisslin,makkot,chelad,limeber,jeelow,sumbark chelad fisslin limeber makkot jeelow
8,9,bimdah,haagle,goorshell,chelad,limeber,jeelow,bimdah chelad haagle limeber goorshell jeelow
9,10,barget,dingep,sumbark,chelad,limeber,jeelow,barget chelad dingep limeber sumbark jeelow
10,11,rakken,makkot,pakrid,chelad,limeber,jeelow,rakken chelad makkot limeber pakrid jeelow
11,12,rakken,dingep,sumbark,chelad,limeber,jeelow,rakken chelad dingep limeber sumbark jeelow