In [ ]:
# for _ in range(1000):
#     selected_permutations = random.sample(valid_permutations, 80)
#     print("Before deleting duplicate elements: ", len(selected_permutations))
#     print("After deleting duplicate elements: ", len(set(selected_permutations)))
#     if len(selected_permutations) != len(set(selected_permutations)):
#         break

# Now you have a dataframe with as balanced an appearance of items as possible.
# print(f"item1 range {(df['item1'].value_counts().max() - df['item1'].value_counts().min())}")
# print(f"item2 range {(df['item2'].value_counts().max() - df['item2'].value_counts().min())}")
# print(f"item3 range {(df['item3'].value_counts().max() - df['item3'].value_counts().min())}")

In [1]:
import random
from itertools import permutations
import pandas as pd
import os
import shutil
import warnings
import random
import numpy as np
from itertools import permutations
import sys

warnings.filterwarnings('ignore')

In [13]:
random.seed(123)

In [247]:
import random
from itertools import permutations
import pandas as pd
import os
import shutil
import warnings
import random
import numpy as np
from itertools import permutations
import sys

warnings.filterwarnings('ignore')

# Define the pool of syllabus items
syllabus_pool = ["barget", "bimdah", "chelad", "dingep", "fisslin", "goorshell",
                "haagle", "jeelow", "limeber", "makkot", "nellby", "pakrid",
                "rakken", "sumbark"]

# Randomly select 10 items from the pool
selected_items = random.sample(syllabus_pool, 10)



# Generate all possible permutations of the selected items
all_permutations = list(permutations(selected_items, 3))
valid_permutations = list(set(all_permutations))


# Randomly select 20 valid permutations
selected_permutations = random.sample(valid_permutations, 160)
selected_permutations = list(set(selected_permutations))

# Create the initial DataFrame
df = pd.DataFrame({
    'trial': range(1, 161),
    'item1': [p[0] for p in selected_permutations],
    'item2': [p[1] for p in selected_permutations],
    'item3': [p[2] for p in selected_permutations]
})

In [305]:
def create_samples(df, value_counts,item_col):
    item_dfs = {}
    
    for name in value_counts.index:
        item_dfs[name] = df[df[item_col]==name].sample(4)
        
    return item_dfs

In [306]:
item1_value_counts = df['item1'].value_counts()
item2_value_counts = df['item2'].value_counts()
item3_value_counts = df['item3'].value_counts()


it1 = create_samples(df, item1_value_counts, 'item1')
it2 = create_samples(df, item2_value_counts, 'item2')
it3 = create_samples(df, item3_value_counts, 'item3')

In [307]:
it1_df = pd.concat(it1.values(),axis=0).reset_index()
it2_df = pd.concat(it2.values(),axis=0).reset_index()
it3_df = pd.concat(it3.values(),axis=0).reset_index()

In [310]:
x = pd.concat([it1_df,it2_df,it3_df],axis=0).reset_index(drop=True)
x['item3'].value_counts()

item3
jeelow     14
bimdah     14
dingep     13
makkot     13
fisslin    13
nellby     12
pakrid     11
haagle     11
sumbark    10
chelad      9
Name: count, dtype: int64

In [181]:

def COUNTER(block,count_manager,item):
    for items in block:
        count_manager[items[item]] = count_manager.get(items[item], 0) + 1
    return count_manager
        
def SORT_COUNTMANAGER(count_manager):
    return dict(sorted(count_manager.items(), key=lambda item: item[1]))

In [196]:
# Randomly select 20 valid permutations
selected_permutations = random.sample(valid_permutations, 80)
selected_permutations = list(set(selected_permutations))

BLOCKS = 4
block_items = {}
count_manager_item1 = {}
count_manager_item2 = {}
count_manager_item3 = {}
CONSTRAINT = 8

# FIRST BLOCK
items = random.choices(selected_permutations,k=20)
print(len(items))
block_items[f'block_{1}'] = items


# maintain counts
count_manager_item1 = COUNTER(items, count_manager_item1, 0)
count_manager_item2 = COUNTER(items, count_manager_item2, 1)
count_manager_item3 = COUNTER(items, count_manager_item3, 2)
# sort 
count_manager_item1 = SORT_COUNTMANAGER(count_manager_item1)
count_manager_item2 = SORT_COUNTMANAGER(count_manager_item2)
count_manager_item3 = SORT_COUNTMANAGER(count_manager_item3)

print(count_manager_item1)
print(count_manager_item2)
print(count_manager_item3)


all_equal = all(value == CONSTRAINT for value in count_manager_item1.values())
while all_equal:
    
    count_manager_item1 = COUNTER(items, count_manager_item1, 0)

20
{'bimdah': 1, 'pakrid': 2, 'goorshell': 2, 'limeber': 2, 'rakken': 3, 'nellby': 3, 'dingep': 3, 'haagle': 4}
{'jeelow': 1, 'dingep': 1, 'fisslin': 2, 'rakken': 2, 'pakrid': 2, 'bimdah': 2, 'goorshell': 3, 'nellby': 7}
{'pakrid': 1, 'goorshell': 2, 'dingep': 2, 'haagle': 2, 'fisslin': 2, 'nellby': 2, 'limeber': 3, 'jeelow': 3, 'bimdah': 3}
{'bimdah': 1, 'pakrid': 2, 'goorshell': 2, 'limeber': 2, 'rakken': 3, 'nellby': 3, 'dingep': 3, 'haagle': 4}
False

In [217]:
# Randomly select 20 valid permutations
selected_permutations = random.sample(valid_permutations, 160)
selected_permutations = list(set(selected_permutations))

# Create the initial DataFrame
df = pd.DataFrame({
    'trial': range(1, 161),
    'item1': [p[0] for p in selected_permutations],
    'item2': [p[1] for p in selected_permutations],
    'item3': [p[2] for p in selected_permutations]
})

print(df['item1'].value_counts())
print(df['item2'].value_counts())
print(df['item3'].value_counts())

item1
dingep       20
limeber      18
bimdah       18
rakken       17
fisslin      15
haagle       15
goorshell    15
pakrid       14
nellby       14
jeelow       14
Name: count, dtype: int64
item2
dingep       25
jeelow       20
limeber      19
haagle       18
nellby       16
fisslin      14
pakrid       14
bimdah       12
goorshell    12
rakken       10
Name: count, dtype: int64
item3
rakken       22
jeelow       20
bimdah       19
pakrid       18
goorshell    16
fisslin      16
haagle       15
limeber      14
dingep       11
nellby        9
Name: count, dtype: int64

In [219]:
df = pd.DataFrame(df['item1'])
df.value_counts()

item1
dingep       20
bimdah       18
limeber      18
rakken       17
fisslin      15
goorshell    15
haagle       15
jeelow       14
nellby       14
pakrid       14
Name: count, dtype: int64

In [222]:
value_counts_df.reset_index()

       item1  count
0     dingep     20
1     bimdah     18
2    limeber     18
3     rakken     17
4    fisslin     15
5  goorshell     15
6     haagle     15
7     jeelow     14
8     nellby     14
9     pakrid     14

In [230]:
# import pandas as pd

# # Sample data with 10 different fruits and initial counts
# data = {'Fruit': ['Apple', 'Banana', 'Cherry', 'Date', 'Elderberry', 'Fig', 'Grape', 'Honeydew', 'Iguana', 'Jackfruit'],
#         'Count': [16, 14, 17, 20, 14, 12, 15, 13, 12, 27]}  # Assuming the initial total sum is 160

# df = pd.DataFrame(data)

# # Calculate the current total sum
# current_total = df['Count'].sum()

# # Desired total sum
# desired_total = 80

# # Calculate the scaling factor
# scaling_factor = desired_total / current_total

# # Update the counts by multiplying with the scaling factor
# df['Count'] = (df['Count'] * scaling_factor).round().astype(int)

# # Adjust the counts to make sure they sum to exactly 80
# while df['Count'].sum() != 80:
#     diff = df['Count'].sum() - 80
#     idx = df['Count'].idxmax()
#     df.at[idx, 'Count'] -= diff

# # Verify that the total sum is now 80
# new_total = df['Count'].sum()

# print(df)
# print("New total sum:", new_total)

In [231]:

# Randomly select 20 valid permutations
selected_permutations = random.sample(valid_permutations, 80)
selected_permutations = list(set(selected_permutations))

# Create the initial DataFrame
df = pd.DataFrame({
    'trial': range(1, 81),
    'item1': [p[0] for p in selected_permutations],
    'item2': [p[1] for p in selected_permutations],
    'item3': [p[2] for p in selected_permutations]
})

# Identify remaining items for case markers
remaining_items = list(set(syllabus_pool) - set(selected_items))

# Randomly select 3 items to be used as case markers
casemarker_items = random.sample(remaining_items, 3)

# Randomly select 3 items to be used as case markers
casemarker_items = random.sample(remaining_items, 3)

# Add case markers to the DataFrame
df['casemarker1'] = casemarker_items[0]
df['casemarker2'] = casemarker_items[1]
df['casemarker3'] = casemarker_items[2]

# Create a list of case marker combinations
case_marker_combinations = ["correlated", "isolated-left", "isolated-center", "isolated-right"]

# Create an empty list to store rows
rows = []

# Create rows for each combination of case markers
for combination in case_marker_combinations:
    # Create a new DataFrame with swapped case markers
    df_new = df.copy()

    # Function to swap case markers for a given row
    def swap_case_markers(row, combination):
        if combination == "isolated-left":
            row['casemarker2'], row['casemarker3'] = row['casemarker3'], row['casemarker2']
        elif combination == "isolated-center":
            row['casemarker1'], row['casemarker3'] = row['casemarker3'], row['casemarker1']
        elif combination == "isolated-right":
            row['casemarker1'], row['casemarker2'] = row['casemarker2'], row['casemarker1']
        return row

    # Identify 50% of rows to swap in df_new
    swap_rows = random.sample(range(len(df_new)), int(len(df_new) * 0.5))

    # Swap casemarkers in df_new for the identified rows
    for row in swap_rows:
        df_new.iloc[row] = swap_case_markers(df_new.iloc[row], combination)

    # Update the 'final' column in df_new
    df_new['final'] = df_new['item1'] + " " + df_new['casemarker1'] + " " + df_new['item2'] + " " + df_new['casemarker2'] + " " + df_new['item3'] + " " + df_new['casemarker3']

    # Label the conditions
    df_new['condition'] = combination

    rows.append(df_new)

# Combine the DataFrames for different combinations
combined_df = pd.concat(rows, ignore_index=True)

# audio_sequences
audio_sequences = []
for row in combined_df[['item1','casemarker1','item2','casemarker2','item3','casemarker3']].iterrows():
    seq = [word+'.wav' for word in row[1].to_list()]
    audio_sequences.append(seq)


combined_df['audio_sequence'] = audio_sequences

# image sequence 
image_sequence = []
for row in combined_df[['item1','item2','item3']].iterrows():
    seq = [image_association[word] for word in row[1].to_list()]
    image_sequence.append(seq)

combined_df['image_sequence'] = image_sequence

KeyError: 'bimdah'