In [4]:
import random
from itertools import permutations
import pandas as pd

# Set seed for reproducibility
random.seed(123)

# Define the pool of syllabus items
syllabus_pool = ["barget", "bimdah", "chelad", "dingep", "fisslin", "goorshell",
                 "haagle", "jeelow", "limeber", "makkot", "nellby", "pakrid",
                 "rakken", "sumbark"]

# Randomly select 10 items from the pool
selected_items = random.sample(syllabus_pool, 10)

# Generate all possible permutations of the selected items
all_permutations = list(permutations(selected_items, 3))

# Filter out invalid permutations (those with repeated items)
valid_permutations = [p for p in all_permutations if len(set(p)) == len(p)]

# Randomly select 20 valid permutations
selected_permutations = random.sample(valid_permutations, 20)

# Create the initial DataFrame
df = pd.DataFrame({
    'trial': range(1, 21),
    'item1': [p[0] for p in selected_permutations],
    'item2': [p[1] for p in selected_permutations],
    'item3': [p[2] for p in selected_permutations]
})

# Identify remaining items for case markers
remaining_items = list(set(syllabus_pool) - set(selected_items))

# Randomly select 3 items to be used as case markers
casemarker_items = random.sample(remaining_items, 3)

# Add case markers to the DataFrame
df['casemarker1'] = casemarker_items[0]
df['casemarker2'] = casemarker_items[1]
df['casemarker3'] = casemarker_items[2]

# Create a concatenated column for items and case markers
df['final'] = df['item1'] + " " + df['casemarker1'] + " " + df['item2'] + " " + df['casemarker2'] + " " + df['item3'] + " " + df['casemarker3']

# Create a new DataFrame with swapped case markers
df_new = df.copy()
swap_rows = random.sample(range(len(df)), int(len(df) * 0.5))  # Identify 50% of rows to swap
df_new.loc[swap_rows, ['casemarker2', 'casemarker3']] = df_new.loc[swap_rows, ['casemarker3', 'casemarker2']]
df_new['final'] = df_new['item1'] + " " + df_new['casemarker1'] + " " + df_new['item2'] + " " + df_new['casemarker2'] + " " + df_new['item3'] + " " + df_new['casemarker3']

# Label the conditions
df['condition'] = "correlated"
df_new['condition'] = "isolated"

# Combine the original and new DataFrames
combined_df = pd.concat([df, df_new], ignore_index=True)

# Save the data to a CSV file
# combined_df.to_csv("data_source.csv", index=False)

combined_df

,trial,item1,item2,item3,casemarker1,casemarker2,casemarker3,final,condition
0,1,rakken,dingep,pakrid,chelad,jeelow,nellby,rakken chelad dingep jeelow pakrid nellby,correlated
1,2,rakken,makkot,pakrid,chelad,jeelow,nellby,rakken chelad makkot jeelow pakrid nellby,correlated
2,3,barget,dingep,sumbark,chelad,jeelow,nellby,barget chelad dingep jeelow sumbark nellby,correlated
3,4,bimdah,haagle,pakrid,chelad,jeelow,nellby,bimdah chelad haagle jeelow pakrid nellby,correlated
4,5,fisslin,goorshell,haagle,chelad,jeelow,nellby,fisslin chelad goorshell jeelow haagle nellby,correlated
5,6,rakken,makkot,fisslin,chelad,jeelow,nellby,rakken chelad makkot jeelow fisslin nellby,correlated
6,7,dingep,goorshell,sumbark,chelad,jeelow,nellby,dingep chelad goorshell jeelow sumbark nellby,correlated
7,8,rakken,dingep,sumbark,chelad,jeelow,nellby,rakken chelad dingep jeelow sumbark nellby,correlated
8,9,goorshell,makkot,sumbark,chelad,jeelow,nellby,goorshell chelad makkot jeelow sumbark nellby,correlated
9,10,haagle,pakrid,rakken,chelad,jeelow,nellby,haagle chelad pakrid jeelow rakken nellby,correlated
10,11,bimdah,haagle,goorshell,chelad,jeelow,nellby,bimdah chelad haagle jeelow goorshell nellby,correlated
11,12,barget,fisslin,haagle,chelad,jeelow,nellby,barget chelad fisslin jeelow haagle nellby,correlated
12,13,sumbark,fisslin,makkot,chelad,jeelow,nellby,sumbark chelad fisslin jeelow makkot nellby,correlated
13,14,fisslin,haagle,bimdah,chelad,jeelow,nellby,fisslin chelad haagle jeelow bimdah nellby,correlated
14,15,makkot,rakken,haagle,chelad,jeelow,nellby,makkot chelad rakken jeelow haagle nellby,correlated
15,16,pakrid,haagle,bimdah,chelad,jeelow,nellby,pakrid chelad haagle jeelow bimdah nellby,correlated
16,17,barget,goorshell,makkot,chelad,jeelow,nellby,barget chelad goorshell jeelow makkot nellby,correlated
17,18,barget,fisslin,makkot,chelad,jeelow,nellby,barget chelad fisslin jeelow makkot nellby,correlated
18,19,rakken,pakrid,haagle,chelad,jeelow,nellby,rakken chelad pakrid jeelow haagle nellby,correlated
19,20,sumbark,haagle,rakken,chelad,jeelow,nellby,sumbark chelad haagle jeelow rakken nellby,correlated
20,1,rakken,dingep,pakrid,chelad,jeelow,nellby,rakken chelad dingep jeelow pakrid nellby,isolated
21,2,rakken,makkot,pakrid,chelad,jeelow,nellby,rakken chelad makkot jeelow pakrid nellby,isolated
22,3,barget,dingep,sumbark,chelad,jeelow,nellby,barget chelad dingep jeelow sumbark nellby,isolated
23,4,bimdah,haagle,pakrid,chelad,jeelow,nellby,bimdah chelad haagle jeelow pakrid nellby,isolated
24,5,fisslin,goorshell,haagle,chelad,jeelow,nellby,fisslin chelad goorshell jeelow haagle nellby,isolated
25,6,rakken,makkot,fisslin,chelad,jeelow,nellby,rakken chelad makkot jeelow fisslin nellby,isolated
26,7,dingep,goorshell,sumbark,chelad,jeelow,nellby,dingep chelad goorshell jeelow sumbark nellby,isolated
27,8,rakken,dingep,sumbark,chelad,jeelow,nellby,rakken chelad dingep jeelow sumbark nellby,isolated
28,9,goorshell,makkot,sumbark,chelad,jeelow,nellby,goorshell chelad makkot jeelow sumbark nellby,isolated
29,10,haagle,pakrid,rakken,chelad,jeelow,nellby,haagle chelad pakrid jeelow rakken nellby,isolated
30,11,bimdah,haagle,goorshell,chelad,jeelow,nellby,bimdah chelad haagle jeelow goorshell nellby,isolated
31,12,barget,fisslin,haagle,chelad,jeelow,nellby,barget chelad fisslin jeelow haagle nellby,isolated
32,13,sumbark,fisslin,makkot,chelad,jeelow,nellby,sumbark chelad fisslin jeelow makkot nellby,isolated
33,14,fisslin,haagle,bimdah,chelad,jeelow,nellby,fisslin chelad haagle jeelow bimdah nellby,isolated
34,15,makkot,rakken,haagle,chelad,jeelow,nellby,makkot chelad rakken jeelow haagle nellby,isolated
35,16,pakrid,haagle,bimdah,chelad,jeelow,nellby,pakrid chelad haagle jeelow bimdah nellby,isolated
36,17,barget,goorshell,makkot,chelad,jeelow,nellby,barget chelad goorshell jeelow makkot nellby,isolated
37,18,barget,fisslin,makkot,chelad,jeelow,nellby,barget chelad fisslin jeelow makkot nellby,isolated
38,19,rakken,pakrid,haagle,chelad,jeelow,nellby,rakken chelad pakrid jeelow haagle nellby,isolated
39,20,sumbark,haagle,rakken,chelad,jeelow,nellby,sumbark chelad haagle jeelow rakken nellby,isolated

### Foil Generation 
##### generating foils (visual), they are two types of foil
#### type 1 (6 trial each block): transposition. for example: ABC, can be transposed into two way: BCA, CAB
#### type 2 (6 trial each block): one item change, for example: ABC can be paired with DBC (D is randomly chose from 10-3 = 7 possible symbols). 
#### There are a total of 3 possible changes (left place, middle, right place), creat two trials for each of the change

In [5]:
# Type1

In [10]:
from itertools import permutations

letters = ['A', 'B', 'C']
cyclic_permutations = []

for perm in permutations(letters):
    cyclic_permutation = ''.join(perm)
    if cyclic_permutation not in cyclic_permutations:
        cyclic_permutations.append(cyclic_permutation)

for perm in cyclic_permutations:
    print(perm)

ABC
ACB
BAC
BCA
CAB
CBA

In [7]:
combined_df[['item1','item2','item3']]

        item1      item2      item3
0      rakken     dingep     pakrid
1      rakken     makkot     pakrid
2      barget     dingep    sumbark
3      bimdah     haagle     pakrid
4     fisslin  goorshell     haagle
5      rakken     makkot    fisslin
6      dingep  goorshell    sumbark
7      rakken     dingep    sumbark
8   goorshell     makkot    sumbark
9      haagle     pakrid     rakken
10     bimdah     haagle  goorshell
11     barget    fisslin     haagle
12    sumbark    fisslin     makkot
13    fisslin     haagle     bimdah
14     makkot     rakken     haagle
15     pakrid     haagle     bimdah
16     barget  goorshell     makkot
17     barget    fisslin     makkot
18     rakken     pakrid     haagle
19    sumbark     haagle     rakken
20     rakken     dingep     pakrid
21     rakken     makkot     pakrid
22     barget     dingep    sumbark
23     bimdah     haagle     pakrid
24    fisslin  goorshell     haagle
25     rakken     makkot    fisslin
26     dingep  goorshell    sumbark
27     rakken     dingep    sumbark
28  goorshell     makkot    sumbark
29     haagle     pakrid     rakken
30     bimdah     haagle  goorshell
31     barget    fisslin     haagle
32    sumbark    fisslin     makkot
33    fisslin     haagle     bimdah
34     makkot     rakken     haagle
35     pakrid     haagle     bimdah
36     barget  goorshell     makkot
37     barget    fisslin     makkot
38     rakken     pakrid     haagle
39    sumbark     haagle     rakken