In [3]:
import random
from itertools import permutations
import pandas as pd

# Set seed for reproducibility
random.seed(123)

# Define the pool of syllabus items
syllabus_pool = ["barget", "bimdah", "chelad", "dingep", "fisslin", "goorshell",
                 "haagle", "jeelow", "limeber", "makkot", "nellby", "pakrid",
                 "rakken", "sumbark"]

# Randomly select 10 items from the pool
selected_items = random.sample(syllabus_pool, 10)

# Generate all possible permutations of the selected items
all_permutations = list(permutations(selected_items, 3))

# Filter out invalid permutations (those with repeated items)
valid_permutations = [p for p in all_permutations if len(set(p)) == len(p)]

# Randomly select 20 valid permutations
selected_permutations = random.sample(valid_permutations, 20)

# Create the initial DataFrame
df = pd.DataFrame({
    'trial': range(1, 21),
    'item1': [p[0] for p in selected_permutations],
    'item2': [p[1] for p in selected_permutations],
    'item3': [p[2] for p in selected_permutations]
})

# Identify remaining items for case markers
remaining_items = list(set(syllabus_pool) - set(selected_items))

# Randomly select 3 items to be used as case markers
casemarker_items = random.sample(remaining_items, 3)

# Add case markers to the DataFrame
df['casemarker1'] = casemarker_items[0]
df['casemarker2'] = casemarker_items[1]
df['casemarker3'] = casemarker_items[2]

# Create a concatenated column for items and case markers
df['final'] = df['item1'] + " " + df['casemarker1'] + " " + df['item2'] + " " + df['casemarker2'] + " " + df['item3'] + " " + df['casemarker3']

# Create a new DataFrame with swapped case markers
df_new = df.copy()

# Identify 50% of rows to swap in df_new
swap_rows = random.sample(range(len(df_new)), int(len(df_new) * 0.5))

# Swap casemarkers in df_new for the identified rows
for row in swap_rows:
    df_new.at[row, 'casemarker2'], df_new.at[row, 'casemarker3'] = df_new.at[row, 'casemarker3'], df_new.at[row, 'casemarker2']

# Update the 'final' column in df_new
df_new['final'] = df_new['item1'] + " " + df_new['casemarker1'] + " " + df_new['item2'] + " " + df_new['casemarker2'] + " " + df_new['item3'] + " " + df_new['casemarker3']


# Label the conditions
df['condition'] = "correlated"
df_new['condition'] = "isolated"

# Combine the original and new DataFrames
combined_df = pd.concat([df, df_new], ignore_index=True)
combined_df

,trial,item1,item2,item3,casemarker1,casemarker2,casemarker3,final,condition
0,1,rakken,dingep,pakrid,jeelow,limeber,chelad,rakken jeelow dingep limeber pakrid chelad,correlated
1,2,rakken,makkot,pakrid,jeelow,limeber,chelad,rakken jeelow makkot limeber pakrid chelad,correlated
2,3,barget,dingep,sumbark,jeelow,limeber,chelad,barget jeelow dingep limeber sumbark chelad,correlated
3,4,bimdah,haagle,pakrid,jeelow,limeber,chelad,bimdah jeelow haagle limeber pakrid chelad,correlated
4,5,fisslin,goorshell,haagle,jeelow,limeber,chelad,fisslin jeelow goorshell limeber haagle chelad,correlated
5,6,rakken,makkot,fisslin,jeelow,limeber,chelad,rakken jeelow makkot limeber fisslin chelad,correlated
6,7,dingep,goorshell,sumbark,jeelow,limeber,chelad,dingep jeelow goorshell limeber sumbark chelad,correlated
7,8,rakken,dingep,sumbark,jeelow,limeber,chelad,rakken jeelow dingep limeber sumbark chelad,correlated
8,9,goorshell,makkot,sumbark,jeelow,limeber,chelad,goorshell jeelow makkot limeber sumbark chelad,correlated
9,10,haagle,pakrid,rakken,jeelow,limeber,chelad,haagle jeelow pakrid limeber rakken chelad,correlated
10,11,bimdah,haagle,goorshell,jeelow,limeber,chelad,bimdah jeelow haagle limeber goorshell chelad,correlated
11,12,barget,fisslin,haagle,jeelow,limeber,chelad,barget jeelow fisslin limeber haagle chelad,correlated
12,13,sumbark,fisslin,makkot,jeelow,limeber,chelad,sumbark jeelow fisslin limeber makkot chelad,correlated
13,14,fisslin,haagle,bimdah,jeelow,limeber,chelad,fisslin jeelow haagle limeber bimdah chelad,correlated
14,15,makkot,rakken,haagle,jeelow,limeber,chelad,makkot jeelow rakken limeber haagle chelad,correlated
15,16,pakrid,haagle,bimdah,jeelow,limeber,chelad,pakrid jeelow haagle limeber bimdah chelad,correlated
16,17,barget,goorshell,makkot,jeelow,limeber,chelad,barget jeelow goorshell limeber makkot chelad,correlated
17,18,barget,fisslin,makkot,jeelow,limeber,chelad,barget jeelow fisslin limeber makkot chelad,correlated
18,19,rakken,pakrid,haagle,jeelow,limeber,chelad,rakken jeelow pakrid limeber haagle chelad,correlated
19,20,sumbark,haagle,rakken,jeelow,limeber,chelad,sumbark jeelow haagle limeber rakken chelad,correlated
20,1,rakken,dingep,pakrid,jeelow,chelad,limeber,rakken jeelow dingep chelad pakrid limeber,isolated
21,2,rakken,makkot,pakrid,jeelow,limeber,chelad,rakken jeelow makkot limeber pakrid chelad,isolated
22,3,barget,dingep,sumbark,jeelow,limeber,chelad,barget jeelow dingep limeber sumbark chelad,isolated
23,4,bimdah,haagle,pakrid,jeelow,limeber,chelad,bimdah jeelow haagle limeber pakrid chelad,isolated
24,5,fisslin,goorshell,haagle,jeelow,chelad,limeber,fisslin jeelow goorshell chelad haagle limeber,isolated
25,6,rakken,makkot,fisslin,jeelow,limeber,chelad,rakken jeelow makkot limeber fisslin chelad,isolated
26,7,dingep,goorshell,sumbark,jeelow,limeber,chelad,dingep jeelow goorshell limeber sumbark chelad,isolated
27,8,rakken,dingep,sumbark,jeelow,chelad,limeber,rakken jeelow dingep chelad sumbark limeber,isolated
28,9,goorshell,makkot,sumbark,jeelow,limeber,chelad,goorshell jeelow makkot limeber sumbark chelad,isolated
29,10,haagle,pakrid,rakken,jeelow,chelad,limeber,haagle jeelow pakrid chelad rakken limeber,isolated
30,11,bimdah,haagle,goorshell,jeelow,limeber,chelad,bimdah jeelow haagle limeber goorshell chelad,isolated
31,12,barget,fisslin,haagle,jeelow,limeber,chelad,barget jeelow fisslin limeber haagle chelad,isolated
32,13,sumbark,fisslin,makkot,jeelow,limeber,chelad,sumbark jeelow fisslin limeber makkot chelad,isolated
33,14,fisslin,haagle,bimdah,jeelow,chelad,limeber,fisslin jeelow haagle chelad bimdah limeber,isolated
34,15,makkot,rakken,haagle,jeelow,limeber,chelad,makkot jeelow rakken limeber haagle chelad,isolated
35,16,pakrid,haagle,bimdah,jeelow,chelad,limeber,pakrid jeelow haagle chelad bimdah limeber,isolated
36,17,barget,goorshell,makkot,jeelow,chelad,limeber,barget jeelow goorshell chelad makkot limeber,isolated
37,18,barget,fisslin,makkot,jeelow,chelad,limeber,barget jeelow fisslin chelad makkot limeber,isolated
38,19,rakken,pakrid,haagle,jeelow,chelad,limeber,rakken jeelow pakrid chelad haagle limeber,isolated
39,20,sumbark,haagle,rakken,jeelow,chelad,limeber,sumbark jeelow haagle chelad rakken limeber,isolated

#### Need to change isolated conditon to middle-right, left-right, left-middle

### Foil Generation 
##### generating foils (visual), they are two types of foil
#### type 1 (6 trial each block): transposition. for example: ABC, can be transposed into two way: BCA, CAB
#### type 2 (6 trial each block): one item change, for example: ABC can be paired with DBC (D is randomly chose from 10-3 = 7 possible symbols). 
#### There are a total of 3 possible changes (left place, middle, right place), creat two trials for each of the change

In [176]:
# Type1

In [185]:
import random
from itertools import permutations
def generate_transposition_foil(items,):
    

    cyclic_permutations = []

    for perm in permutations(items):
        cyclic_permutation = ','.join(perm)
        if cyclic_permutation not in cyclic_permutations:
            cyclic_permutations.append(cyclic_permutation)

    trans_foils = [[foil] for foil in cyclic_permutations[1:]]
    return trans_foils

In [186]:
test_df_transposition = test_df[test_df['foil_category']=='transposition']
test_df_itemchange = test_df[test_df['foil_category']=='itemchange']


# TRANSPOSITION
list_of_foils = []
print("Generating Transposition Foils.")
for row in test_df_transposition[['item1','item2','item3']].iterrows():
    target_items = row[1].to_list()
    trans_foils = generate_transposition_foil(target_items)
    trans_foils = [item[0].split(',') for item in trans_foils]
    transposition_foil = random.choice(trans_foils)
    list_of_foils.append(transposition_foil)
test_df_transposition['foil'] = list_of_foils

# ITEM CHANGE
print("Generating Item Change Foils.")
list_of_foils = []
for row in test_df_itemchange[['item1','item2','item3']].iterrows():
    target_items = row[1].to_list()
    ##print(target_items)
    possibilities =  list(set(selected_items) - set(target_items))
    #print(possibilities)
    item_change = random.choice(possibilities)
    positions = [0,1,2] # left, center, middle
    position_selection = random.choice(positions)
    #print(item_change)
    #print(position_selection)
    
    itemchange_foils = target_items
    itemchange_foils[position_selection] = item_change
    list_of_foils.append(itemchange_foils)
    
    
test_df_itemchange['foil'] = list_of_foils


# REORDERING 

test_df = pd.concat([test_df_transposition, test_df_itemchange],axis=0)
# reordering
corr_df = test_df[test_df['condition']=='correlated']
iso_df = test_df[test_df['condition']=='isolated']

final_test_df = pd.concat([corr_df,iso_df],axis=0)
final_test_df

Generating Transposition Foils.
Generating Item Change Foils.

/var/folders/5r/pnlff12n2d55g65_tnn3b1pw0000gn/T/ipykernel_11702/2778485847.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_df_transposition['foil'] = list_of_foils
/var/folders/5r/pnlff12n2d55g65_tnn3b1pw0000gn/T/ipykernel_11702/2778485847.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_df_itemchange['foil'] = list_of_foils

,trial,item1,item2,item3,casemarker1,casemarker2,casemarker3,final,condition,foil_category,foil
0,16,pakrid,haagle,bimdah,limeber,nellby,chelad,pakrid limeber haagle nellby bimdah chelad,correlated,transposition,"[haagle, bimdah, pakrid]"
1,11,bimdah,haagle,goorshell,limeber,nellby,chelad,bimdah limeber haagle nellby goorshell chelad,correlated,transposition,"[haagle, goorshell, bimdah]"
2,4,bimdah,haagle,pakrid,limeber,nellby,chelad,bimdah limeber haagle nellby pakrid chelad,correlated,transposition,"[pakrid, haagle, bimdah]"
3,15,makkot,rakken,haagle,limeber,nellby,chelad,makkot limeber rakken nellby haagle chelad,correlated,transposition,"[haagle, makkot, rakken]"
4,8,rakken,dingep,sumbark,limeber,nellby,chelad,rakken limeber dingep nellby sumbark chelad,correlated,transposition,"[dingep, rakken, sumbark]"
5,7,dingep,goorshell,sumbark,limeber,nellby,chelad,dingep limeber goorshell nellby sumbark chelad,correlated,transposition,"[sumbark, goorshell, dingep]"
6,12,barget,fisslin,haagle,limeber,nellby,chelad,barget limeber fisslin nellby haagle chelad,correlated,itemchange,"[barget, fisslin, bimdah]"
7,20,sumbark,haagle,rakken,limeber,nellby,chelad,sumbark limeber haagle nellby rakken chelad,correlated,itemchange,"[sumbark, haagle, barget]"
8,5,fisslin,goorshell,haagle,limeber,nellby,chelad,fisslin limeber goorshell nellby haagle chelad,correlated,itemchange,"[fisslin, goorshell, pakrid]"
9,6,rakken,makkot,fisslin,limeber,nellby,chelad,rakken limeber makkot nellby fisslin chelad,correlated,itemchange,"[rakken, sumbark, fisslin]"
10,10,haagle,pakrid,rakken,limeber,nellby,chelad,haagle limeber pakrid nellby rakken chelad,correlated,itemchange,"[haagle, pakrid, sumbark]"
11,17,barget,goorshell,makkot,limeber,nellby,chelad,barget limeber goorshell nellby makkot chelad,correlated,itemchange,"[barget, bimdah, makkot]"
12,3,barget,dingep,sumbark,limeber,nellby,chelad,barget limeber dingep nellby sumbark chelad,isolated,transposition,"[sumbark, dingep, barget]"
13,14,fisslin,haagle,bimdah,limeber,nellby,chelad,fisslin limeber haagle nellby bimdah chelad,isolated,transposition,"[bimdah, haagle, fisslin]"
14,16,pakrid,haagle,bimdah,limeber,nellby,chelad,pakrid limeber haagle nellby bimdah chelad,isolated,transposition,"[haagle, bimdah, pakrid]"
15,4,bimdah,haagle,pakrid,limeber,nellby,chelad,bimdah limeber haagle nellby pakrid chelad,isolated,transposition,"[bimdah, pakrid, haagle]"
16,15,makkot,rakken,haagle,limeber,nellby,chelad,makkot limeber rakken nellby haagle chelad,isolated,transposition,"[haagle, makkot, rakken]"
17,10,haagle,pakrid,rakken,limeber,nellby,chelad,haagle limeber pakrid nellby rakken chelad,isolated,transposition,"[rakken, pakrid, haagle]"
18,19,rakken,pakrid,haagle,limeber,nellby,chelad,rakken limeber pakrid nellby haagle chelad,isolated,itemchange,"[sumbark, pakrid, haagle]"
19,1,rakken,dingep,pakrid,limeber,nellby,chelad,rakken limeber dingep nellby pakrid chelad,isolated,itemchange,"[rakken, dingep, fisslin]"
20,12,barget,fisslin,haagle,limeber,nellby,chelad,barget limeber fisslin nellby haagle chelad,isolated,itemchange,"[barget, fisslin, makkot]"
21,18,barget,fisslin,makkot,limeber,nellby,chelad,barget limeber fisslin nellby makkot chelad,isolated,itemchange,"[pakrid, fisslin, makkot]"
22,8,rakken,dingep,sumbark,limeber,nellby,chelad,rakken limeber dingep nellby sumbark chelad,isolated,itemchange,"[rakken, dingep, goorshell]"
23,20,sumbark,haagle,rakken,limeber,nellby,chelad,sumbark limeber haagle nellby rakken chelad,isolated,itemchange,"[bimdah, haagle, rakken]"

### Archived Logic for Test

In [69]:

# Randomly select 12 items from selected_permutations
test_selected_permutations = random.sample(selected_permutations, 12)

# Identify the remaining items for case markers
remaining_items = list(set(syllabus_pool) - set(selected_items))

# Randomly select 12 items to be used as case markers for the test_df
test_casemarker_items = random.sample(remaining_items, 3)

# Create the initial DataFrame for the test_df
test_df = pd.DataFrame({
    'trial': range(1, 13),
    'item1': [p[0] for p in test_selected_permutations],
    'item2': [p[1] for p in test_selected_permutations],
    'item3': [p[2] for p in test_selected_permutations],
    'casemarker1': test_casemarker_items[0],  
    'casemarker2': test_casemarker_items[1],  
    'casemarker3': test_casemarker_items[2],
})

# Create a concatenated column for items and case markers in test_df
test_df['target'] = test_df['item1'] + " " + test_df['casemarker1'] + " " + test_df['item2'] + " " + test_df['casemarker2'] + " " + test_df['item3'] + " " + test_df['casemarker3']

test_df

,trial,item1,item2,item3,casemarker1,casemarker2,casemarker3,target
0,1,barget,fisslin,makkot,chelad,limeber,jeelow,barget chelad fisslin limeber makkot jeelow
1,2,pakrid,haagle,bimdah,chelad,limeber,jeelow,pakrid chelad haagle limeber bimdah jeelow
2,3,barget,goorshell,makkot,chelad,limeber,jeelow,barget chelad goorshell limeber makkot jeelow
3,4,fisslin,haagle,bimdah,chelad,limeber,jeelow,fisslin chelad haagle limeber bimdah jeelow
4,5,barget,fisslin,haagle,chelad,limeber,jeelow,barget chelad fisslin limeber haagle jeelow
5,6,goorshell,makkot,sumbark,chelad,limeber,jeelow,goorshell chelad makkot limeber sumbark jeelow
6,7,rakken,dingep,pakrid,chelad,limeber,jeelow,rakken chelad dingep limeber pakrid jeelow
7,8,sumbark,fisslin,makkot,chelad,limeber,jeelow,sumbark chelad fisslin limeber makkot jeelow
8,9,bimdah,haagle,goorshell,chelad,limeber,jeelow,bimdah chelad haagle limeber goorshell jeelow
9,10,barget,dingep,sumbark,chelad,limeber,jeelow,barget chelad dingep limeber sumbark jeelow
10,11,rakken,makkot,pakrid,chelad,limeber,jeelow,rakken chelad makkot limeber pakrid jeelow
11,12,rakken,dingep,sumbark,chelad,limeber,jeelow,rakken chelad dingep limeber sumbark jeelow